version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $ca-central-1 | docker login --username AWS --password-stdin 099014799395.dkr.ecr.$ca-central-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t majid-ecs-app .
      - echo Tagging the Docker image...
      - docker tag majid-ecs-app:latest 099014799395.dkr.ecr.$ca-central-1.amazonaws.com/majid-ecs-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 099014799395.dkr.ecr.$ca-central-1.amazonaws.com/majid-ecs-app:latest
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
